#!/usr/bin/env python3
"""Rebuild tasks/board.md from task frontmatter (rules: .cursor/rules/task-files.mdc).

Usage: scripts/sync_board.py           rewrite tasks/board.md
       scripts/sync_board.py --check   exit 1 if tasks/board.md is out of date (used by pre-commit)
       scripts/sync_board.py --staged  like --check, but compares the staged versions
"""
import pathlib
import re
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from check_transitions import frontmatter  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
BOARD = "tasks/board.md"
ORDER = ["BACKLOG", "READY", "IN_PROGRESS", "CODE_REVIEW", "CHANGES_REQUESTED", "MERGED", "TESTING", "BUG",
         "READY_FOR_DEPLOY", "DEPLOYING", "RELEASED", "BLOCKED"]
PRIORITY = ["CRITICAL", "HIGH", "MEDIUM", "LOW"]
HEADER = """# Task Board

Index of all tasks. Source of truth is each task file. Rules: `.cursor/rules/task-files.mdc`.
Generated by `python3 scripts/sync_board.py` — do not edit rows by hand.

| ID | Title | Type | Priority | Status | Assignee | Depends on | Updated |
|----|-------|------|----------|--------|----------|------------|---------|
"""


def rank(values, value):
    return values.index(value) if value in values else len(values)


def render(files):
    """files: iterable of (filename, text) for tasks/TASK-*.md."""
    rows = []
    for name, text in files:
        f = frontmatter(text)
        deps = f.get("depends_on", "").strip("[] ")
        rows.append((
            rank(ORDER, f.get("status")), rank(PRIORITY, f.get("priority")), f.get("id", name),
            f"| [{f.get('id', name)}]({name}) | {f.get('title', '')} | {f.get('type', '')} | {f.get('priority', '')} "
            f"| {f.get('status', '')} | {f.get('assignee', '')} | {deps or '—'} | {f.get('updated', '')} |",
        ))
    return HEADER + "".join(r[3] + "\n" for r in sorted(rows))


def working_tree():
    return render((p.name, p.read_text()) for p in sorted((ROOT / "tasks").glob("TASK-*.md")))


def staged():
    names = subprocess.run(["git", "ls-files", "--cached", "tasks/"], cwd=ROOT, capture_output=True,
                           text=True).stdout.split()
    files = [(n.split("/")[-1], subprocess.run(["git", "show", f":{n}"], cwd=ROOT, capture_output=True,
                                               text=True).stdout)
             for n in names if re.match(r"^tasks/TASK-\d{3,}-[^/]+\.md$", n)]
    board = subprocess.run(["git", "show", f":{BOARD}"], cwd=ROOT, capture_output=True, text=True).stdout
    return render(files), board


def main(argv):
    if "--staged" in argv:
        expected, actual = staged()
    else:
        expected = working_tree()
        path = ROOT / BOARD
        if "--check" not in argv:
            path.write_text(expected)
            return 0
        actual = path.read_text() if path.exists() else ""
    if expected != actual:
        print(f"{BOARD} is out of date: run `python3 scripts/sync_board.py` and stage it.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
